//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblProject
    {
        public int ProjectID { get; set; }
        [Required(ErrorMessage = "Bu kýsým boþ býrakýlamaz!")]
        public string ProjectTitle { get; set; }
        public string ProjectDescription { get; set; }
        public string projectimageurl { get; set; }
    }
}
