//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProfile
    {
        public int ProfileID { get; set; }
        public string ProfileTitle { get; set; }
        public string profileDescription { get; set; }
        public string Name { get; set; }
        public string mail { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string socialnetwork1 { get; set; }
        public string socialnetwork2 { get; set; }
        public string socialnetwork3 { get; set; }
        public string socialnetwork4 { get; set; }
    }
}
