//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblReferences
    {
        public int ReferenceID { get; set; }
        [Required(ErrorMessage = "Bu kýsým boþ býrakýlamaz!")]
        public string NameSurname { get; set; }
        public string Job { get; set; }
        public string Comment { get; set; }
        public string ImageURL { get; set; }
    }
}
